module.exports.KEYBOARD = require('./keyboard')
module.exports.USERROLES = require('./userRoles')
module.exports.DESTENATION = require('./destenation')
module.exports.MIMETYPE = require('./mimeType')
module.exports.MESSAGES = require('./messages')
