module.exports.launch = require('./launch')
module.exports.start = require('./start')
module.exports.update = require('./update')
module.exports.uploadImage = require('./uploadImage')
module.exports.createRole = require('./createRole')
